---
version: '3.3'
services:
  rdtclient:
    image: rogerfar/rdtclient
    container_name: rdtclient
    environment:
      - PUID=501
      - PGID=100
      - TZ=America/Los_Angeles
    volumes:
      - /Users/mittalmak/dev/docker/rdt-client/data/db:/data/db
      - /Volumes/Download:/data/downloads
    logging:
       driver: json-file
       options:
          max-size: 10m
    ports:
      - 6500:6500
    restart: unless-stopped