upstreams:
  groups:
    default:
      - 1.1.1.1
      - 8.8.8.8
blocking:
  denylists:
    ads:
      - https://raw.githubusercontent.com/ZingyAwesome/easylists-for-pihole/master/easylist.txt
      - https://raw.githubusercontent.com/ZingyAwesome/easylists-for-pihole/master/easyprivacy.txt
      - https://big.oisd.nl
      - https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Hosts/GoodbyeAds.txt
      - https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-Xiaomi-Extension.txt
      - https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-Samsung-AdBlock.txt
      - https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-YouTube-AdBlock.txt
  clientGroupsBlock:
    default:
      - ads
  blockType: zeroIP
  blockTTL: 6h
ports:
  dns: 53
  http: 4000
